CREATE OR REPLACE SECURE VIEW VW_SATELLITE_READY_CLAIMS AS
SELECT ASSET_NAME, CLAIM_FOR_SATELLITE, EXPECTED_PARAMETER, COORDINATE_HINT
FROM SATELLITE_AUDIT;

-- Grant access to the VIEW, not the raw table.
GRANT USAGE ON DATABASE ECO_AGENT_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA AUDIT_LOGS TO ROLE PUBLIC;
GRANT SELECT ON VIEW VW_SATELLITE_READY_CLAIMS TO ROLE PUBLIC;