USE ROLE ACCOUNTADMIN; 
USE DATABASE ECO_AGENT_DB;
USE SCHEMA AUDIT_LOGS;

-- Re-create the view
CREATE OR REPLACE SECURE VIEW VW_SATELLITE_READY_CLAIMS AS
SELECT ASSET_NAME, CLAIM_FOR_SATELLITE, EXPECTED_PARAMETER, COORDINATE_HINT
FROM SATELLITE_AUDIT;

-- Permissions
GRANT USAGE ON DATABASE ECO_AGENT_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA AUDIT_LOGS TO ROLE PUBLIC;
GRANT SELECT ON VIEW VW_SATELLITE_READY_CLAIMS TO ROLE PUBLIC;

-- Verify table
SHOW VIEWS LIKE 'VW_SATELLITE_READY_CLAIMS';