-- Initial Setup for Eco-Agent
USE ROLE SYSADMIN;

-- 1. Create Infrastructure
CREATE OR REPLACE WAREHOUSE ECO_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60;
CREATE OR REPLACE DATABASE ECO_AGENT_DB;
CREATE OR REPLACE SCHEMA AUDIT_LOGS;

-- 2. Create "Evidence" Stage for PDFs
CREATE OR REPLACE STAGE ESG_REPORTS_STAGE 
DIRECTORY = (ENABLE = TRUE) 
ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- 3. Create the Results Table
CREATE OR REPLACE TABLE AUDIT_RESULTS (
    COMPANY_NAME STRING,
    CLAIM_EXTRACTED STRING,
    SATELLITE_VERDICT STRING,
    HYPOCRISY_SCORE FLOAT,
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);